export const environment = {
  apiUrl: 'http://127.0.0.1:8000/api/v1',
  useCompanySettingsMock: true,
  useCompaniesAdministrationMock: false,
  enableCompaniesAdministrationFallback: true,
  useClientsAdministrationMock: true,
  enableClientsAdministrationFallback: false,
  useProductsAdministrationMock: true,
  enableProductsAdministrationFallback: false,
  useVendorsAdministrationMock: true,
  enableVendorsAdministrationFallback: false,
  useDriversAdministrationMock: true,
  enableDriversAdministrationFallback: false,
  useRoutesAdministrationMock: true,
  enableRoutesAdministrationFallback: false,
  useSuppliersAdministrationMock: true,
  enableSuppliersAdministrationFallback: false,
  useEquipmentsAdministrationMock: true,
  enableEquipmentsAdministrationFallback: false,
  useSecurityAdministrationMock: false,
  enableSecurityAdministrationFallback: true,
  useAuditLogsMock: false,
  enableAuditLogsFallback: true,
};
