"""crear_tablas_MAESTROS

Revision ID: 1e1ff32f96ff
Revises: ff0b46fca310
Create Date: 2026-04-13 22:59:52.120442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1ff32f96ff'
down_revision: Union[str, Sequence[str], None] = 'ff0b46fca310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'usuario_empresa_config', 'perfiles_empresa', ['perfil_id'], ['id'], source_schema='seguridad', referent_schema='seguridad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_empresa_config', schema='seguridad', type_='foreignkey')
    # ### end Alembic commands ###
