"""Init ERP Corregido

Revision ID: 20d7e466856d
Revises: 
Create Date: 2026-04-05 01:39:37.175131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20d7e466856d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('zona_horaria', sa.String(length=50), nullable=False),
    sa.Column('formato_fecha', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('fecha_inicio_operacion', sa.DateTime(), nullable=True),
    sa.Column('configuraciones_iniciales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit'),
    sa.UniqueConstraint('nombre_empresa'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_configuraciones_empresa_id'), 'configuraciones', ['empresa_id'], unique=True, schema='configuracion')
    op.create_index(op.f('ix_configuracion_configuraciones_id'), 'configuraciones', ['id'], unique=False, schema='configuracion')
    op.create_table('empresa_sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_empresa_sector_id'), 'empresa_sector', ['id'], unique=False, schema='configuracion')
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_modulos_id'), 'modulos', ['id'], unique=False, schema='configuracion')
    op.create_table('parametros_generales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_parametros_generales_id'), 'parametros_generales', ['id'], unique=False, schema='configuracion')
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=150), nullable=True),
    sa.Column('empresa_id', sa.String(length=50), nullable=True),
    sa.Column('modulo', sa.String(length=150), nullable=True),
    sa.Column('accion', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload_antes', sa.JSON(), nullable=True),
    sa.Column('payload_despues', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_auditoria_empresa_id'), 'auditoria', ['empresa_id'], unique=False, schema='seguridad')
    op.create_index(op.f('ix_seguridad_auditoria_id'), 'auditoria', ['id'], unique=False, schema='seguridad')
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefono_fijo', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_usuarios_email'), 'usuarios', ['email'], unique=True, schema='seguridad')
    op.create_index(op.f('ix_seguridad_usuarios_id'), 'usuarios', ['id'], unique=False, schema='seguridad')
    op.create_index(op.f('ix_seguridad_usuarios_username'), 'usuarios', ['username'], unique=True, schema='seguridad')
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['configuracion.modulos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='configuracion'
    )
    op.create_index(op.f('ix_configuracion_menus_id'), 'menus', ['id'], unique=False, schema='configuracion')
    op.create_table('perfiles_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('permisos', sa.JSON(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['configuracion.configuraciones.empresa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_perfiles_empresa_id'), 'perfiles_empresa', ['id'], unique=False, schema='seguridad')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('permisos', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['configuracion.configuraciones.empresa_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_roles_id'), 'roles', ['id'], unique=False, schema='seguridad')
    op.create_table('usuario_empresa_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.String(length=50), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['seguridad.roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['seguridad.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_usuario_empresa_config_id'), 'usuario_empresa_config', ['id'], unique=False, schema='seguridad')
    op.create_table('usuarios_empresas_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.String(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['configuracion.configuraciones.empresa_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['seguridad.roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['seguridad.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='seguridad'
    )
    op.create_index(op.f('ix_seguridad_usuarios_empresas_roles_id'), 'usuarios_empresas_roles', ['id'], unique=False, schema='seguridad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguridad_usuarios_empresas_roles_id'), table_name='usuarios_empresas_roles', schema='seguridad')
    op.drop_table('usuarios_empresas_roles', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_usuario_empresa_config_id'), table_name='usuario_empresa_config', schema='seguridad')
    op.drop_table('usuario_empresa_config', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_roles_id'), table_name='roles', schema='seguridad')
    op.drop_table('roles', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_perfiles_empresa_id'), table_name='perfiles_empresa', schema='seguridad')
    op.drop_table('perfiles_empresa', schema='seguridad')
    op.drop_index(op.f('ix_configuracion_menus_id'), table_name='menus', schema='configuracion')
    op.drop_table('menus', schema='configuracion')
    op.drop_index(op.f('ix_seguridad_usuarios_username'), table_name='usuarios', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_usuarios_id'), table_name='usuarios', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_usuarios_email'), table_name='usuarios', schema='seguridad')
    op.drop_table('usuarios', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_auditoria_id'), table_name='auditoria', schema='seguridad')
    op.drop_index(op.f('ix_seguridad_auditoria_empresa_id'), table_name='auditoria', schema='seguridad')
    op.drop_table('auditoria', schema='seguridad')
    op.drop_index(op.f('ix_configuracion_parametros_generales_id'), table_name='parametros_generales', schema='configuracion')
    op.drop_table('parametros_generales', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_modulos_id'), table_name='modulos', schema='configuracion')
    op.drop_table('modulos', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_empresa_sector_id'), table_name='empresa_sector', schema='configuracion')
    op.drop_table('empresa_sector', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_configuraciones_id'), table_name='configuraciones', schema='configuracion')
    op.drop_index(op.f('ix_configuracion_configuraciones_empresa_id'), table_name='configuraciones', schema='configuracion')
    op.drop_table('configuraciones', schema='configuracion')
    # ### end Alembic commands ###
