"""Actualizacion_FullStack_pt1

Revision ID: 2d0e3ea96cdc
Revises: b671df04049f
Create Date: 2026-04-24 11:10:29.936212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d0e3ea96cdc'
down_revision: Union[str, Sequence[str], None] = 'b671df04049f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perfiles_empresa', 'empresa_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='seguridad')
    op.alter_column('perfiles_empresa', 'estado',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True,
               schema='seguridad')
    op.drop_column('perfiles_empresa', 'permisos', schema='seguridad')
    op.drop_column('perfiles_empresa', 'fecha_actualizacion', schema='seguridad')
    op.alter_column('roles', 'descripcion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='seguridad')
    op.alter_column('roles', 'empresa_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='seguridad')
    op.drop_column('usuarios', 'rol', schema='seguridad')
    op.alter_column('usuarios_empresas_roles', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='seguridad')
    op.alter_column('usuarios_empresas_roles', 'empresa_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='seguridad')
    op.alter_column('usuarios_empresas_roles', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='seguridad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios_empresas_roles', 'rol_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='seguridad')
    op.alter_column('usuarios_empresas_roles', 'empresa_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='seguridad')
    op.alter_column('usuarios_empresas_roles', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='seguridad')
    op.add_column('usuarios', sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='seguridad')
    op.alter_column('roles', 'empresa_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='seguridad')
    op.alter_column('roles', 'descripcion',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='seguridad')
    op.add_column('perfiles_empresa', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='seguridad')
    op.add_column('perfiles_empresa', sa.Column('permisos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False), schema='seguridad')
    op.alter_column('perfiles_empresa', 'estado',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               schema='seguridad')
    op.alter_column('perfiles_empresa', 'empresa_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='seguridad')
    # ### end Alembic commands ###
