"""crear_tablas_Inventarios_SCM_WMS

Revision ID: b671df04049f
Revises: 1e1ff32f96ff
Create Date: 2026-04-21 22:52:38.293144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b671df04049f'
down_revision: Union[str, Sequence[str], None] = '1e1ff32f96ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
