"""crear_tabla_productos_inventario

Revision ID: ff0b46fca310
Revises: 00263eb19278
Create Date: 2026-04-05 23:39:44.401588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0b46fca310'
down_revision: Union[str, Sequence[str], None] = '00263eb19278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditoria', 'modulo',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               schema='seguridad')
    op.alter_column('auditoria', 'accion',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               schema='seguridad')
    op.alter_column('auditoria', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='seguridad')
    op.drop_index(op.f('ix_seguridad_auditoria_empresa_id'), table_name='auditoria', schema='seguridad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_seguridad_auditoria_empresa_id'), 'auditoria', ['empresa_id'], unique=False, schema='seguridad')
    op.alter_column('auditoria', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='seguridad')
    op.alter_column('auditoria', 'accion',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               schema='seguridad')
    op.alter_column('auditoria', 'modulo',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               schema='seguridad')
    # ### end Alembic commands ###
